apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rms-docker-img
  temrms-docker-img
    metadata:
      labels:
        app: rms-docker-img
    spec:
      containers:
      - name: rms-container
        image: bryan19191919191919/orbit:abc12345
        ports:
        - containerPort: 5050