apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orbit
  template:
    metadata:
      labels:
        app: orbit
    spec:
      containers:
      - name: orbit
        image: bryan19191919191919/orbit:abc12345
        ports:
        - containerPort: 5050