name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run backend tests with Mocha
      - name: Run Backend Tests
        run: npm run backend-test

      # Step 5: Ensure .nyc_output exists
      - name: Check Backend Coverage Directory
        run: ls .nyc_output || echo "Directory not found"

      # Step 6: Upload backend coverage report
      - name: Upload Backend Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: .nyc_output/  # Ensure this path matches where nyc output is stored

  frontend-tests:
    runs-on: ubuntu-latest

    needs: backend-tests

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Instrument frontend code
      - name: Instrument Frontend Code
        run: npm run frontend-instrument

      # Step 5: Run frontend tests with Cypress
      - name: Run Frontend Tests
        run: npm run frontend-test

      # Step 6: Ensure .nyc_output exists
      - name: Check Frontend Coverage Directory
        run: ls .nyc_output || echo "Directory not found"

      # Step 7: Upload frontend coverage report
      - name: Upload Frontend Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: .nyc_output/  # Ensure this path matches where nyc output is stored